<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>91b024fd-fa6f-46f2-881b-d02a89a7078f</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DuongNhan.ApiService\DuongNhan.ApiService.csproj" />
    <ProjectReference Include="..\DuongNhan.Web\DuongNhan.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

</Project>