<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>7b9e5b6f-1d43-4427-8263-8f4458373d14</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DuongNhan.ServiceDefaults\DuongNhan.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DuongNhan.Shared\DuongNhan.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="HaveIBeenPwned.Client" />
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DuongNhan.Tests" />
  </ItemGroup>

</Project>